//! The fbank against torchaudio's own Kaldi implementation.
//!
//! This is the only test in the repo that exists because the failure mode is
//! *invisible*. A wrong window shape, a wrong mel formula, a missing
//! pre-emphasis — none of them crash, none of them produce obviously bad
//! numbers, and the cosine similarity downstream keeps returning values in
//! [0,1] that look like answers. Without a reference there is no way to know,
//! and "it clusters" is not evidence: noise clusters too.
//!
//! The fixture is generated by `torchaudio.compliance.kaldi.fbank` with the
//! parameters recorded inside it. The input is two sines rather than a wav
//! file so both sides can produce bit-identical samples from arithmetic.

use super::*;

fn reference() -> (usize, usize, Vec<f32>) {
    let text = std::fs::read_to_string("tests/fixtures/fbank.json")
        .expect("run the generator in BACKLOG M7.4 to make tests/fixtures/fbank.json");
    let v: serde_json::Value = serde_json::from_str(&text).expect("fixture parses");
    let frames = v["frames"].as_u64().unwrap() as usize;
    let bands = v["bands"].as_u64().unwrap() as usize;
    let feats = v["feats"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|row| {
            row.as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_f64().unwrap() as f32)
        })
        .collect();
    (frames, bands, feats)
}

/// The same signal the generator used, from arithmetic rather than a file.
///
/// A linear chirp across the whole band, and that is the point. It started as
/// two sines, and two sines left most of the 80 filters looking at silence —
/// changing Kaldi's mel constant from 1127 to 1125 moved no number the test
/// could see. A signal that excites every filter is what makes the filterbank
/// layout testable at all.
fn signal() -> Vec<f32> {
    const F0: f64 = 50.0;
    const F1: f64 = 7800.0;
    const SECONDS: f64 = 1.0;
    let k = (F1 - F0) / SECONDS;
    (0..16_000)
        .map(|n| {
            let t = n as f64 / 16_000.0;
            (0.5 * (2.0 * std::f64::consts::PI * (F0 * t + 0.5 * k * t * t)).sin()) as f32
        })
        .collect()
}

#[test]
fn the_frame_count_is_kaldis() {
    // `snip_edges=true`: whole windows only, tail dropped rather than padded.
    // Padding invents audio and the model would embed it.
    let (frames, _, _) = reference();
    assert_eq!(frame_count(16_000), frames);
    assert_eq!(
        frame_count(399),
        0,
        "a window that does not fit is no frame"
    );
    assert_eq!(frame_count(400), 1);
    assert_eq!(frame_count(560), 2);
}

#[test]
fn the_features_match_torchaudios_kaldi_fbank() {
    let (frames, bands, expected) = reference();
    assert_eq!(bands, MEL_BANDS);
    let got = compute(&signal());
    assert_eq!(got.len(), frames * bands, "shape");

    let mut worst = 0.0f32;
    let mut worst_at = (0, 0);
    for f in 0..frames {
        for b in 0..bands {
            let i = f * bands + b;
            let d = (got[i] - expected[i]).abs();
            if d > worst {
                worst = d;
                worst_at = (f, b);
            }
        }
    }
    // The tolerance is on the log-mel value, where the model's own inputs
    // live. Measured, by breaking each convention in turn and reading the
    // worst deviation off this very assertion:
    //
    //   Hann instead of povey            2.94
    //   pre-emphasis 0.97 -> 0.95        1.48
    //   low cutoff 20 Hz -> 0            3.28
    //   mel curve 700 -> 690             0.81
    //
    // and one that does *not* move it, which is worth knowing: Kaldi's 1127
    // can be 1125 with no effect at all. It multiplies every mel value, and
    // the filter edges are built from the same function, so a uniform scale
    // cancels out of every comparison and every weight ratio. The constant
    // that shapes the curve is the 700.
    assert!(
        worst < 0.01,
        "worst deviation {worst} at frame {} band {} (got {}, reference {})",
        worst_at.0,
        worst_at.1,
        got[worst_at.0 * bands + worst_at.1],
        expected[worst_at.0 * bands + worst_at.1]
    );
}
